services:
    jonasarts\Bundle\PaginationBundle\Counter\CounterRenderer:
        arguments: [ "@twig" ]
    jonasarts\Bundle\PaginationBundle\PageSizeSelector\PageSizeSelectorRenderer:
        arguments: [ "@twig" ]
    jonasarts\Bundle\PaginationBundle\Pagination\PaginatonRenderer:
        arguments: [ "@twig" ]